### ISSUE TITLE
MacOS Big Sur: "technical_error" returned, loadNibNamed returns nil

### ISSUE THREAD

**Issue by minfrin** [open-eid/chrome-token-signing#199]
While running chrome-token-signing through the debugger in Xcode 12.4 on Big Sur, the plugin fails as follows:

`{"result":"technical_error","nonce":1,"ver":1}
`

This is caused by the following line of code, which returns nil:

`[[NSBundle bundleForClass:CertificateSelection.class] loadNibNamed:@"CertificateSelection" owner:self topLevelObjects:nil]
`

https://github.com/open-eid/chrome-token-signing/blob/master/host-osx/CertificateSelection.mm#L122

It is not clear at this point why this should fail in the debugger but succeed in the final released plugin. It is possible also that the plugin has regressed between the last release and now.

Doing normal builds (running "make") on the released v1.1.3 and v1.1.4 releases both have the same problem on Big Sur.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
