### ISSUE TITLE
Pin dialog only accepting digits in OSX

### ISSUE THREAD

**Issue by wzoet** [open-eid/chrome-token-signing#213]
Hi,

We are using the plugin with Safenet eTokens. This works great in windows and recently we got some questions about OSX.
After adding the right ATR and some further testing, we found that we cannot use the plugin at this moment because we use alfanumeric pins on our tokens and the plugin only allows for digits.

I am not able to find what should be changed in PINDialog to allow for letter input. I do see that the code behind is using UTF8String of the textbox, so I suspect that it is just a filter on top of the dialog preventing input of alfanumeric characters.

Could you tell me what I should change in the dialog markup to allow for alfanumeric input of the PIN? Are there other places in code that I should change to allow for this?

Thanks in advance!

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
