### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by kurtuluso** [open-eid/chrome-token-signing#215]
What do you think about introducing a configuration file?
It can provide behavior information and driver/library information so that the signing will be more flexible.

i.e. Completely new tokens can be introduced without new build

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
