### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by rinu** [open-eid/chrome-token-signing#218]
The Linux instructions just don't work.
https://github.com/open-eid/chrome-token-signing/wiki/Extension-removal

How do I actually get rid of this extension on Chrome on Ubuntu 22.04?

**Comment by rinu** [comment]
It must be something in `~/.config/google-chrome`. When it was removed the extension was installed but not under a policy lock so it could be removed. Permanently deleting all of my profiles is not an option.

**Comment by rinu** [comment]
Reinstalling Chrome let keep my configs and removed the policy lock.

**Comment by kristelmerilain** [comment]
How did you install the Token Signing?

**Comment by rinu** [comment]
It was installed with the installer sh script probably in late 2020.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
