### ISSUE TITLE
Chrome OS support

### ISSUE THREAD

**Issue by martinl** [open-eid/chrome-token-signing#37]
Google has released smartcard connector framework for ChromeOS devices: https://github.com/GoogleChrome/chromeos_smart_card_connector

Please add ID-card support for Chrome OS

**Comment by jeffmcneill** [comment]
Please add ChromeOS support. This is an important platform that is doing nothing but grow.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
